[dependencies]
smithay = { version = "0.7", features = [
    "backend_vulkan",
    "renderer_vulkan",
    "desktop",
    "wayland_frontend",
    "backend_drm",
    "backend_gbm"
] }
calloop = "0.10"
env_logger = "0.9"
log = "0.4"
